### ISSUE TITLE
ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by mariojacobo** [Hexadite/acs-keyvault-agent#13]
This has worked for us in the past, however with a brand new cluster, we are getting the following error when initializing: 

$ kubectl logs app-65559b75cf-zjm2c -c keyvault-agent
|2018-08-31 12:34:39,684|INFO |1|140644736362240|keyvault-agent|Grabbing secrets from Key Vault
|2018-08-31 12:34:39,684|INFO |1|140644736362240|keyvault-agent|Parsing Service Principle file from: /host/azure.json
Traceback (most recent call last):
  File "main.py", line 196, in <module>
    KeyVaultAgent().grab_secrets()
  File "main.py", line 52, in __init__
    self._parse_sp_file()
  File "main.py", line 65, in _parse_sp_file
    sp_data = json.load(sp_file)
  File "/usr/local/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/local/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", 
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", 

Any ideas ? 

Thanks

**Comment by mariojacobo** [comment]
Tried with another Kubernetes version 1.11.1, same issue: 

$ kubectl logs app-5b69df9698-kb4pn -c keyvault-agent
|2018-08-31 14:34:52,308|INFO |1|140396165961472|keyvault-agent|Grabbing secrets from Key Vault
|2018-08-31 14:34:52,308|INFO |1|140396165961472|keyvault-agent|Parsing Service Principle file from: /host/azure.json
Traceback (most recent call last):
  File "./main.py", line 286, in <module>
    KeyVaultAgent().grab_secrets()
  File "./main.py", line 186, in grab_secrets
    client = self._get_client()
  File "./main.py", line 82, in _get_client
    self._parse_sp_file()
  File "./main.py", line 69, in _parse_sp_file
    sp_data = json.load(sp_file)
  File "/usr/local/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/local/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by mariojacobo** [comment]
deep diving into this, we found the issue. something has changed on the AKS side, and the /etc/kubernetes/azure.json file on AKS is Invalid. 

Wrong: 
"cloudProviderBackoff": True,
"cloudProviderRatelimit": True,

Correct: 
"cloudProviderBackoff": true,
"cloudProviderRatelimit": true,

**Comment by idanlevin** [comment]
@mariojacobo thanks for troubleshooting and helping fix this bug in acs-engine.

can we close this issue now? it's already fixed in - 
https://github.com/Azure/acs-engine/pull/3774

**Comment by idanlevin** [comment]
closing due to no-activity and existing fix
