### ISSUE TITLE
CREATE_KUBERNETES_SECRETS not working

### ISSUE THREAD

**Issue by ezgambac** [Hexadite/acs-keyvault-agent#20]
I have set the env variable as the tutorial says:

        - name: CREATE_KUBERNETES_SECRETS
          value: "true"

It appears set in the environment part of kubectl describe pods:

    Environment:
      SERVICE_PRINCIPLE_FILE_PATH:  /host/azure.json
      CREATE_KUBERNETES_SECRETS:    true

However, the logs from the container show that the code is failing in grab_secrets, however this method should never have been called according to main.py:
```python
if __name__ == '__main__':
    _logger.info('Grabbing secrets from Key Vault')
    if os.getenv('CREATE_KUBERNETES_SECRETS','false').lower() == "true":
        KeyVaultAgent().grab_secrets_kubernetes_objects()
    else:
        KeyVaultAgent().grab_secrets()
    _logger.info('Done!')
```

|2019-08-15 20:12:27,195|INFO |1|140086269146880|keyvault-agent|Grabbing secrets from Key Vault
|2019-08-15 20:12:27,195|INFO |1|140086269146880|keyvault-agent|Parsing Service Principle file from: /host/azure.json
|2019-08-15 20:12:27,195|INFO |1|140086269146880|keyvault-agent|Parsing Service Principle file completed
Traceback (most recent call last):
  File "main.py", line 182, in <module>
    KeyVaultAgent().grab_secrets()
  File "main.py", line 89, in grab_secrets
    self._secrets_output_folder = os.path.join(output_folder, "secrets")
  File "/usr/lib/python2.7/posixpath.py", line 70, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'

**Comment by ezgambac** [comment]
Also, doing a printenv shows that the variable is set:

kubectl logs -p api-validation-dev-private-78686bd64c-t42wx -c keyvault-agent
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=aks-agentpool-69837850-1
SERVICE_PRINCIPLE_FILE_PATH=/host/azure.json
CREATE_KUBERNETES_SECRETS=true

**Comment by ezgambac** [comment]
Was using old image, disregard issue.
