### ISSUE TITLE
Default Service Account in current namespace forbidden list kubernetes secret in current namespace

### ISSUE THREAD

**Issue by emre141** [Hexadite/acs-keyvault-agent#30]
Hi,
I am trying to deploy  acs-keyvault-agent/example/acs-keyvault-deployment.yaml

The current code tried to list kubernetes secret under conn namespace by system:serviceaccount:conn:default account and this account has not permission to list secret object at current namespace.

Is it alternative service account to using any action on kubernetes cluster or namesapce ?

Traceback (most recent call last):
  File "./main.py", line 374, in <module>
    KeyVaultAgent().grab_secrets_kubernetes_objects()
  File "./main.py", line 248, in grab_secrets_kubernetes_objects
    self._create_kubernetes_secret_objects(key_name, secret.value, secret_type)
  File "./main.py", line 199, in _create_kubernetes_secret_objects
    secrets_list = self._get_kubernetes_secrets_list()
  File "./main.py", line 146, in _get_kubernetes_secrets_list
    api_response = api_instance.list_namespaced_secret(namespace=self._secrets_namespace)
  File "/usr/local/lib/python2.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 12838, in list_namespaced_secret
    (data) = self.list_namespaced_secret_with_http_info(namespace, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 12941, in list_namespaced_secret_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 321, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/usr/local/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 155, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/local/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 342, in request
    headers=headers)
  File "/usr/local/lib/python2.7/site-packages/kubernetes/client/rest.py", line 231, in GET
    query_params=query_params)
  File "/usr/local/lib/python2.7/site-packages/kubernetes/client/rest.py", line 222, in request
    raise ApiException(http_resp=r)
kubernetes.client.rest.ApiException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Date': 'Wed, 08 Apr 2020 10:27:12 GMT', 'Audit-Id': 'ef4302f4-6091-4253-913f-c3f4f7847c08', 'Content-Length': '285', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"secrets is forbidden: User \"system:serviceaccount:conn:default\" cannot list resource \"secrets\" in API group \"\" in the namespace \"conn\"","reason":"Forbidden","details":{"kind":"secrets"},"code":403}

**Comment by idanlevin** [comment]
You define the service account in the deployment object, so you should either add the RBAC permissions to list/create secrets to the default service account, or use an alternative service account.

**Comment by emre141** [comment]
thank you It solved my problem
